<a href="https://colab.research.google.com/github/prolabfin/Algoritmos-basicos-java/blob/main/Copia_de_MODULO3_ACTIVIDAD_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# . Dadas 2 matrices con dimensiones similares, ¿cómo obtener una salida
# de matriz en la que cada elemento es una suma de elementos de las 2
# matrices? (solo puede usar numpy como librería, si realiza la matriz
# con otro paquete el ejercicio no es válido)

import numpy as np

# Definimos las dos matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Verificamos que las dimensiones de ambas matrices sean iguales
if matrix1.shape == matrix2.shape:
    # Sumamos elemento a elemento las dos matrices
    output_matrix = matrix1 + matrix2
    print(output_matrix)
else:
    print("Las dimensiones de las matrices no son iguales.")



[[ 6  8]
 [10 12]]


In [ ]:
# Cree una matriz de identidad de dimensión 4

import numpy as np

# Creamos una matriz de identidad de dimensión 4
identity_matrix = np.eye(4)

print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# convertir una matriz binaria a booleana 



import numpy as np

# Creamos una matriz numpy binaria
binary_matrix = np.array([[0, 1], [1, 0]])

# Convertimos la matriz binaria a una matriz booleana
boolean_matrix = binary_matrix.astype(bool)

print(boolean_matrix)





[[False  True]
 [ True False]]


In [ ]:
# Genere una secuencia de números en forma de matriz numpy de 0 a
# 100 con espacios de 2 números, por ejemplo: 0, 2, 4 .

import numpy as np

# Generamos la secuencia de números de 0 a 100 con espacios de 2
sequence = np.arange(0, 101, 2)

print(sequence)


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
